image: node:latest

before_script:
  - apt-get update
  - apt-get -y install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common python-software-properties libffi-dev curl make checkinstall
  - npm i node-gyp -g
  - npm i node-pre-gyp -g
  - npm i

cache:
  paths:
  - node_modules/

test:
  script:
    - yarn test
