# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Node 全栈
tagline:          generator-node-fullstack
description:      "这是一个专注于真实生产场景的 Node 全栈工程生成器..."
url:              https://github.com/huso-io/generator-node-fullstack
baseurl:          /

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/huso-io/generator-node-fullstack
